### ISSUE TITLE
trying to understand the syntax

### ISSUE THREAD

**Issue by olets** [welldone-software/gulp-rebase-css-urls#1]
In the readme you give this example:

<hr>

> ## Example
> 
> ```
> + src
>     - file.css
>     + fldr
>         - image.jpg
>         - file2.css
> ```
> 
> Where 'file.css' contents are:
> 
> ``` css
> .a{
>     background-image: url("fldr/image.jpg");
> }
> ```
> 
> and 'file2.css' contents are:
> 
> ``` css
> .b{
>     background-image: url("image.jpg");
> }
> ```
> 
> And the task:
> 
> ``` js
> var rebaseCssUrls = require('gulp-rebase-css-urls'),
>     concat = require('gulp-concat');
> 
> gulp.task('concat-css-files', ['copy-image-file'], function(){
>     return gulp.src('src/**/*.css')
>         .pipe(rebaseCssUrls(srcDir))
>         .pipe(concat('bundle.css'))
>         .pipe(gulp.dest(dstDir));
> });
> ```
> 
> Results in a directory like so:
> 
> ```
> + dst
>     - bundle.css
>     + fldr
>         - image.jpg
> ```
> 
> And a bundle.css contents like so:
> 
> ``` css
> .a{
>     background-image: url("fldr/image.jpg");
> }
> .b{
>     background-image: url("fldr/image.jpg");
> }
> ```

<hr>

That seems to assume `dstDir` has been defined as `dstDir = './dst'`.

Should `srcDir` be defined as `srcDir = 'fldr'`? Or maybe `srcDir = dstDir + '/fldr'`?

**Comment by vzaidman** [comment]
before concatenating the csses, rebaseCssUrls(srcDir) makes sure they all are based on the same folder, for example on a css above
`background-image: url("image.jpg");`
becomes
`background-image: url("fldr/image.jpg");`
so you can safely concat them without changing the location of the image

**Comment by vzaidman** [comment]
updated the readme a bit so it will be easier to understand

**Comment by olets** [comment]
I guess I should just go look at the source, but could you add the `dstDir` and `srcDir` definitions to the readme, or just provide the paths instead of using variables? Then anyone else who finds this plugin will know how to use it

**Comment by vzaidman** [comment]
ok
